In [1]:
import glob

In [8]:
data_annotation_path = '../BINARY_PLANTS/labels'

In [9]:
list_annotations = sorted([x for x in glob.glob(data_annotation_path + '/**')])

In [10]:
list_annotations

['../BINARY_PLANTS/labels/sample_0.json',
 '../BINARY_PLANTS/labels/sample_1.json',
 '../BINARY_PLANTS/labels/sample_10.json',
 '../BINARY_PLANTS/labels/sample_11.json',
 '../BINARY_PLANTS/labels/sample_12.json',
 '../BINARY_PLANTS/labels/sample_13.json',
 '../BINARY_PLANTS/labels/sample_14.json',
 '../BINARY_PLANTS/labels/sample_15.json',
 '../BINARY_PLANTS/labels/sample_16.json',
 '../BINARY_PLANTS/labels/sample_17.json',
 '../BINARY_PLANTS/labels/sample_18.json',
 '../BINARY_PLANTS/labels/sample_19.json',
 '../BINARY_PLANTS/labels/sample_2.json',
 '../BINARY_PLANTS/labels/sample_20.json',
 '../BINARY_PLANTS/labels/sample_21.json',
 '../BINARY_PLANTS/labels/sample_22.json',
 '../BINARY_PLANTS/labels/sample_23.json',
 '../BINARY_PLANTS/labels/sample_24.json',
 '../BINARY_PLANTS/labels/sample_25.json',
 '../BINARY_PLANTS/labels/sample_26.json',
 '../BINARY_PLANTS/labels/sample_27.json',
 '../BINARY_PLANTS/labels/sample_28.json',
 '../BINARY_PLANTS/labels/sample_29.json',
 '../BINARY_PL

In [30]:
import json
import numpy as np

In [62]:
def get_labels_from_json(json_file_path, resized_image_size):
    # Opening JSON file
    f = open(json_file_path)
    data = json.load(f)
    f.close()

    ori_img_height = data['height']
    ori_img_width = data['width']

    bbox_label = []
    for i in range(data['nb_of_plants_rows']):
        x_min = data[f'row_{i}']['xmin']
        y_min = data[f'row_{i}']['ymin']
        x_max = data[f'row_{i}']['xmax']
        y_max = data[f'row_{i}']['ymax']
        
        if x_min > x_max:
            x_min, x_max = x_max, x_min

        #In order to find the resized coordinates, we must multiply the ratio of the resized image compared to its original to the coordinates.
        x_min = float((resized_image_size/ori_img_width)*x_min)
        y_min = float((resized_image_size/ori_img_height)*y_min)
        x_max = float((resized_image_size/ori_img_width)*x_max)
        y_max = float((resized_image_size/ori_img_height)*y_max)

        generated_box_info = [x_min, y_min, x_max, y_max]

        #append each object's class label and the bounding box label (converted to Faster R-CNN format) into the list initialized earlier.
        bbox_label.append(np.asarray(generated_box_info, dtype='float32'))


    return np.asarray(bbox_label)

In [68]:
get_labels_from_json(f'/Users/amir/Desktop/plant_row_detection/generate_image/data/labels/sample_{3}.json',512)

array([[ 30.72   ,   0.     , 131.41333, 510.29333],
       [225.28   ,   0.     , 245.76   , 510.29333],
       [322.56   ,   0.     , 460.8    , 510.29333]], dtype=float32)

In [69]:
bboxes = []
for i in range(50):
    data = get_labels_from_json(f'/Users/amir/Desktop/plant_row_detection/BINARY_PLANTS/labels/sample_{i}.json',480)
    bboxes.append(data)


In [70]:
bboxes

[array([[ 28.8,   0. , 185.6, 478.4],
        [180.8,   0. , 273.6, 478.4],
        [256. ,   0. , 433.6, 478.4],
        [331.2,   0. , 520. , 284.8]], dtype=float32),
 array([[-49.6,   0. , 232. , 478.4],
        [188.8,   0. , 307.2, 478.4],
        [300.8,   0. , 532.8, 457.6]], dtype=float32),
 array([[-48. ,   0. , 139.2, 406.4],
        [150.4,   0. , 270.4, 478.4],
        [243.2,   0. , 510.4, 478.4]], dtype=float32),
 array([[  3.2,   0. , 172.8, 478.4],
        [123.2,   0. , 235.2, 478.4],
        [216. ,   0. , 321.6, 478.4],
        [276.8,   0. , 441.6, 478.4],
        [339.2,   0. , 516.8, 329.6]], dtype=float32),
 array([[-41.6,   0. , 110.4, 273.6],
        [ 24. ,   0. , 166.4, 478.4],
        [140.8,   0. , 228.8, 478.4],
        [196.8,   0. , 348.8, 478.4],
        [252.8,   0. , 468.8, 478.4]], dtype=float32),
 array([[-19.2,   0. , 262.4, 478.4],
        [139.2,   0. , 316.8, 478.4],
        [288. ,   0. , 406.4, 478.4],
        [342.4,   0. , 531.2, 350.4]], dt

In [77]:
bboxes[0][0]

array([ 28.8,   0. , 185.6, 478.4], dtype=float32)

In [97]:
a = np.array([bboxes[0][0][0], bboxes[0][0][3]])
b = np.array([bboxes[0][0][0], bboxes[0][0][1]])
c = np.array([bboxes[0][0][2], bboxes[0][0][3]])

In [98]:
bboxes[0][0][0]

28.8

In [103]:
a = np.array([76,299])
b = np.array([76,0])
c = np.array([1,299])

In [105]:
print(a,b,c)

[ 76 299] [76  0] [  1 299]


In [120]:
import numpy as np

ba = a - b
bc = c - b
print(ba, bc)
cosine_angle = np.dot(ba, bc) / (np.linalg.norm(ba) * np.linalg.norm(bc))
print(cosine_angle.shape)
angle = np.arccos(cosine_angle)

print(np.degrees(angle))

[  0 299] [-75 299]
()
14.081322750137785


In [132]:
def get_angle(xmin,ymin,xmax,ymax):
    a = np.array([xmin, ymax])
    b = np.array([xmin, ymin])
    c = np.array([xmax, ymax])
    ba = a - b
    bc = c - b
    cosine_angle = np.dot(ba, bc) / (np.linalg.norm(ba) * np.linalg.norm(bc))
    angle = np.arccos(cosine_angle)
    if xmin > xmax:
        return -np.degrees(angle)
    else:
        return np.degrees(angle)

In [133]:
get_angle(57,0,10,299)

-8.933261605966267